version: '3.8'

services:
  app:
    image: 'task-1:latest'
    build:
      context: .
    container_name: app
    depends_on:
      - db
    ports:
          - 8000:8080
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/demo
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root

  db:
    image: 'postgres:13.1'
    container_name: db
    restart: always
    ports:
    - 5432:5432
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=demo